
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS payment_mode VARCHAR NOT NULL DEFAULT 'CASH';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS transaction_type VARCHAR NOT NULL DEFAULT 'out';

ALTER TABLE expenses DROP COLUMN IF EXISTS currency;
